-- Limpa os dados antigos para não duplicar
DELETE FROM "EscalaMapping";
DELETE FROM "VinculoMapping";

-- 1. TIPOS DE VÍNCULO (OK)
INSERT INTO "VinculoMapping" ("sigla", "nome") VALUES
                                                   ('SCP', '200204-Distribuição de Lucros'),
                                                   ('PJ', '200220- Prestação de Serviços Médicos'),
                                                   ('PJ 1', '200220- Prestação de Serviços Médicos');

-- 2. MAPEAMENTO DE ESCALA (CORRIGIDO)
INSERT INTO "EscalaMapping" ("empresa", "origem", "destino") VALUES
                                                                 ('Vitallis', 'Vitallis - Fusam Neurocirurgia', '2027-Fusam-Neurocirurgia'),
                                                                 ('Vitallis', 'Vitallis - Lagoinha Especialidades', '2026-Lagoinha-Especialidades'),
                                                                 ('Vitallis', 'Vitallis - Monteiro Lobato PA', '2028-Monteiro Lobato-PA'),
                                                                 ('Vitallis', 'Vitallis - Monteiro Lobato UBS', '2029-Monteiro Lobato-Especialidades'),
                                                                 ('Vitallis', 'Vitallis - São Bento do Sapucaí', '2008-São Bento do Sapucaí-Plantão Médico'),
                                                                 ('Vitallis', 'Vitallis - SAP Cardiologista', '2025-SAP-Cardiologista'),
                                                                 ('Vitallis', 'Vitallis - SAP Neuroped', 'Vitallis - SAP Neuroped'),
                                                                 ('Vitallis', 'Vitallis - Sarapuí PA', 'Vitallis - Sarapuí PA'),
                                                                 ('Vitallis', 'Vitallis - SJC Credenciamento 02/2023', '2020-SJC-Credenciameto 02/2023'),
                                                                 ('SHM', 'CEISP - Clinico Geral', '2071 - CEISP SERVIÇOS EDUCACIONAIS'),
                                                                 ('SHM', 'SHM - Bauru TJSP', '2076-TJ BAURU'),
                                                                 ('SHM', 'SHM - Campinas TJSP', '2077-TJ CAMPINAS'),
                                                                 ('SHM', 'SHM - Cejam Barueri Ortopedia', '2084-CEJAM Ortopedia'),
                                                                 ('SHM', 'SHM - Cejam Pariquera-Açu Fisiatra', '2073-CEJAM FISIATRA'),
                                                                 ('SHM', 'SHM - Cejam Santos Otorrino', '2075-CEJAM OTORRINO'),
                                                                 ('SHM', 'SHM - Fernandópolis UPA', '2040-Fernandopolis-Plantões'),
                                                                 ('SHM', 'SHM - Fusam Cirurgia Geral', '2054-Fusam Cirurgia'),
                                                                 ('SHM', 'SHM - Fusam Pronto Atendimento Adulto', '2057-Fusam PSA'),
                                                                 ('SHM', 'SHM - Iaras', '2013-Iaras - Atenção Básica'),
                                                                 ('SHM', 'SHM - Jacareí - Cred02 - UBS Parque Santo Antonio', '2061-Jacareí-Cred. Pediatra'),
                                                                 ('SHM', 'SHM - Jacareí - Cred02 - UMSF Cidade Salvador', '2061-Jacareí-Cred. Pediatra'),
                                                                 ('SHM', 'SHM - Jacareí - Cred02 - UMSF Jd. Imperial', '2061-Jacareí-Cred. Pediatra'),
                                                                 ('SHM', 'SHM - Jacareí - Cred02 - UMSF PMEC', '2061-Jacareí-Cred. Pediatra'),
                                                                 ('SHM', 'SHM - Jacareí - Cred02 - UMSF Pq. Meia Lua', '2061-Jacareí-Cred. Pediatra'),
                                                                 ('SHM', 'SHM - Jacareí - Cred02 - UMSF Santa Cruz dos Lázaros', '2061-Jacareí-Cred. Pediatra'),
                                                                 ('SHM', 'SHM - Jacareí - Cred02 - UMSF. Rio Comprido', '2061-Jacareí-Cred. Pediatra'),
                                                                 ('SHM', 'SHM - Jacareí - Cred03 - Caps AD', '2062-Jacareí Cred. CAPS'),
                                                                 ('SHM', 'SHM - Jacareí - Cred03 - Caps II', '2062-Jacareí Cred. CAPS'),
                                                                 ('SHM', 'SHM - Jacarei Casa do Abraço', '2061-Jacareí-Cred. Pediatra'),
                                                                 ('SHM', 'SHM - Jacareí CS', 'SHM - Jacareí CS'),
                                                                 ('SHM', 'SHM - Mandirituba HM', '2072-Mandirituba'),
                                                                 ('SHM', 'SHM - OS João Marchesi', '2056-Caraguatatuba-Serviços Terceiros'),
                                                                 ('SHM', 'SHM - Paraibuna Especialidades', '2083-CISMETRO-Paraibuna'),
                                                                 ('SHM', 'SHM - Pinda CAPS Infantil', '2029- Pinda CAPS'),
                                                                 ('SHM', 'SHM - Pinda CEM', '2010-Pinda-Endocrinologista'),
                                                                 ('SHM', 'SHM - Pinda EMAD', '2036-Pinda EMAD'),
                                                                 ('SHM', 'SHM - Pinda Saúde Mental', '2011-Pinda - Saúde Mental'),
                                                                 ('SHM', 'SHM - Piquete Especialidades', '2069-Piquete Especialidades'),
                                                                 ('SHM', 'SHM - Piquete PA', '2067-Piquete PA'),
                                                                 ('SHM', 'SHM - Ribeirão Preto TJSP', '2078- TJ RIBEIRAO PRETO'),
                                                                 ('SHM', 'SHM - Santa Branca - UBS II', '2060-Santa Branca-UBS'),
                                                                 ('SHM', 'SHM - Santa Branca PA', '2059-Santa Branca-PA'),
                                                                 ('SHM', 'SHM - Santa Branca UBS Central', '2060-Santa Branca-UBS'),
                                                                 ('SHM', 'SHM - Santos TJSP', '2079- TJ SANTOS'),
                                                                 ('SHM', 'SHM - São Bento Especialidades', '2085-São Bento do Sapucaí-Especialidades'),
                                                                 ('SHM', 'SHM - São Jose do Rio Preto TJSP', '2080- TJ SAO JOSE DO RIO PRETO'),
                                                                 ('SHM', 'SHM - SAP Especialidades', 'SHM - SAP Especialidades'),
                                                                 ('SHM', 'SHM - SAP PA', '2014-SAP - Plantão Médico'),
                                                                 ('SHM', 'SHM - SJC Cred 01/2025', '2086-S.1j.Campos-Credenciamento 01-2025'),
                                                                 ('SHM', 'SHM - SJC Credenciamento', '2008-SJC-Credenciamento 02-2018'),
                                                                 ('SHM', 'SHM - Sorocaba TJSP', '2082 - TJ SOROCABA'),
                                                                 ('SHM', 'SHM - Tarumã Pronto Atendimento', '2070 - Tarumã PA'),
                                                                 ('SHM', 'SHM - Taubaté Psicologia', '2068-Taubaté Psicólogos'),
                                                                 ('SHM', 'SHM- São José dos Campos TJSP', '2081 - TJ SAO JOSE DOS CAMPOS');